### ISSUE TITLE
Understanding the total time required to finish run

### ISSUE THREAD

**Issue by Anto007** [DominikBuchner/BOLDigger2#14] opened 2024-06-24 08:01 UTC
Thank you very much for bringing out BOLDigger2. My testing of this new version of BOLDigger with small fasta file containing 6 sequences was successful. I am, however, now trying to assign taxonomy to around 13K sequences via BOLDigger2 (command-line I used: `boldigger2 identify ASVs.fa -thresholds 98`) and I'm at the below step after having started the run 24 hrs back. Looking at the log below, I get the idea that the job is likely to run for 2+ days (49 hrs). I realize this is a huge query dataset and so, I don't mind the large computational time that may be required. It's just that I was hoping to get a rough estimate as to when my final results are going to be available given my current run stats (of course, I'm aware that a lot of this also depends on the Internet connection speed, BOLD server status etc.). Thank you very much in advance for your inputs.

```
Downloading top 100 hits: 100%|█████████████████████████████| 13147/13147 [16:05:40<00:00,  4.41s/it]
09:36:57: Species level top 100 records successfully downloaded.
09:36:57: Performing second login for requesting links from the all records database.
09:36:57: Trying to log in.
09:36:59: Login successful.
09:37:10: Starting to gather download links from the all records database.
09:40:38: Query size stays at 50.                                                                    
09:44:14: Query size stays at 50.                                                                    
09:47:39: Query size stays at 50.                                                                    
09:50:46: Query size stays at 50.                                                                    
09:55:47: BOLD did not respond. Retrying with reduced query size of 45.                              
10:00:48: BOLD did not respond. Retrying with reduced query size of 40.                              
10:05:49: BOLD did not respond. Retrying with reduced query size of 35.                              
10:10:50: BOLD did not respond. Retrying with reduced query size of 30.                              
10:15:51: BOLD did not respond. Retrying with reduced query size of 25.                              
10:20:52: BOLD did not respond. Retrying with reduced query size of 20.                              
10:25:53: BOLD did not respond. Retrying with reduced query size of 15.                              
10:30:18: Query size updated to 20.                                                                  
10:33:22: Query size updated to 25.                                                                  
10:36:22: Query size updated to 30.                                                                  
10:39:32: Query size updated to 35.                                                                  
Generating download links:   2%|▋                           | 290/12517 [1:02:21<49:03:51, 14.45s/it] 
```

**Comment by Anto007** [comment] 2024-06-24 08:04
Just a quick update: Query size has got updated to 50 and so, can I hope this run to be finished within the next 24 hrs (since 17 hrs is displayed in the latest log)?

```
11:00:30: Query size stays at 50.                                                                    
Generating download links:   4%|█▎                          | 560/12517 [1:23:20<17:27:35,  5.26s/it]
```

**Comment by DominikBuchner** [comment] 2024-06-24 09:19
Hi Anto,
for those large datasets  it will take multiple days to finish. At your current state I'd estimate another 24h at least, however this is hard to estimate, since it depends on a lot of things I cannot control. It will need to download all the links it generated from the 2nd round + all the additional data.

**Comment by Anto007** [comment] 2024-06-24 09:48
@DominikBuchner many thanks for your prompt response and I completely understand your point. Will close this issue for now.

**Comment by Anto007** [comment] 2024-06-26 06:24
Sorry, I'm reopening this. The run for this dataset has not finished despite running for more than 3 days and this morning, I found it terminated with the below messages. Any ideas as to what might be going on here @DominikBuchner Many thanks in advance. 

P.S. I'm now attempting to resume this job by entering the same initial command-line  

```
04:25:20: Downloaded top 100 hits of all records for ASV_5231                                        
Downloading top 100 hits:  96%|███████████████████████████▉ | 12033/12517 [18:42:22<36:34,  4.53s/it]Traceback (most recent call last):
  File "/home/tools/conda_python3.10_env/bin/boldigger2", line 8, in <module>
    sys.exit(main())
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/boldigger2/__main__.py", line 87, in main
    id_engine_coi.main(
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 654, in main
    asyncio.run(
  File "/home/tools/conda_python3.10_env/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/tools/conda_python3.10_env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 385, in as_session
    return await tqdm_asyncio.gather(*tasks, desc="Downloading top 100 hits")
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/tqdm/asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/home/tools/conda_python3.10_env/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 351, in limit_concurrency
    return await as_request(
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 226, in as_request
    response_table = pd.read_html(
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/pandas/io/html.py", line 1240, in read_html
    return _parse(
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/pandas/io/html.py", line 1003, in _parse
    raise retained
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/pandas/io/html.py", line 983, in _parse
    tables = p.parse_tables()
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/pandas/io/html.py", line 249, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "/home/tools/conda_python3.10_env/lib/python3.10/site-packages/pandas/io/html.py", line 598, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found
Downloading top 100 hits:  96%|███████████████████████████▉ | 12033/12517 [18:42:37<45:09,  5.60s/it]
```

**Comment by DominikBuchner** [comment] 2024-06-26 08:02
Just restarting with the same command should fix it and it should continue at the point where it stopped. If this is not the case, please upload all files generated to far so I can try to reproduce this error.

**Comment by DominikBuchner** [comment] 2024-06-27 06:19
Any news here, or can I close the issue?

**Comment by Anto007** [comment] 2024-06-27 06:55
Thanks for checking on this. The run hasn't finished yet and I'm seeing messages such as "BOLD API overloaded" and so on. I would like to wait and see if this run will ultimately finish without errors and then close this issue.

**Comment by Anto007** [comment] 2024-06-30 06:16
@DominikBuchner The above BOLDigger2 run for 13K sequences got terminated again with the error
_Line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.boldsystems.org', port=80): Max retries exceeded with url:_

I've restarted it but this is really the 7th day of running. I've yet another comparatively smaller job of nearly 4K sequences and it has not finished despite now running for more than 5 days. I believe BOLDigger version 1 would have taken less than 6 hours to output the results for 4K sequences. The only reason I had to stop using version 1 is cos' it had started to give me a login-related issue (an error which popped out of the blue one day and that which wasn't there in my early days of using the version 1). Is there any way that users can go back to using version 1? If things stand as they are, I'm not sure if BOLDigger2 will ultimately end up being as useful as the version 1 and I worry that many users like me will be forced to abandon altogether the use of BOLDigger tool (which would be a real shame considering how useful the tool originally was). Apologies for the bluntness in my rant and I realize that perhaps changes at the BOLD server end might also be proving disadvantageous to your intentions.

**Comment by DominikBuchner** [comment] 2024-06-30 09:59
Hi jant, I fixed the login issue for boldigger-cline which should be fully
operational again. Regarding your rant: I get your frustration however I
did serious Benchmarking to make sure boldigger2 is faster despite much
more data being downloaded. Bold recently limited their API bandwidth to 3
requests per minute from the former 40 per minute, that's why the
additional data download takes much longer now.

Would you be willing to upload your fasta here, so I can use it for another
benchmark?

Best Dominik

Jant007 ***@***.***> schrieb am So., 30. Juni 2024, 08:16:

**Comment by Anto007** [comment] 2024-06-30 11:02
Thank you very much @DominikBuchner for your prompt response and I truly appreciate your bench-marking efforts. Sure, I can share with you here the smaller dataset (fasta file with .txt extension to comply with the GitHub attachment policy) out of the two (n=4689 sequences). 
[ASVs-no-contam-numts-final-clean.fa.txt](https://github.com/user-attachments/files/16044099/ASVs-no-contam-numts-final-clean.fa.txt)

boldigger-cline still throws up errors for me and I wouldn't have been surprised if I have had issues since the beginning. The strange thing is that errors started cropping up only a couple of months back and not anytime before. Up until that point I was successful in getting the results all the time and I've not made any changes in my conda environment either. Below is the code I used for the same fasta file as above but reformatted via seqkit (seqkit seq -w0 ASVs-no-contam-numts-final-clean.fa > 2line_ASVs-no-contam-numts-final-clean.fa)

```
boldigger-cline --version
2.2.1
boldigger-cline ie_coi username password 2line_ASVs-no-contam-numts-final-clean.fa boldigger1_results 50
Traceback (most recent call last):
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/tools/conda_python3.9_env/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x15537a6857c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='boldsystems.org', port=443): Max retries exceeded with url: /index.php/Login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15537a6857c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tools/conda_python3.9_env/bin/boldigger-cline", line 8, in <module>
    sys.exit(main())
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/boldigger_cline/__main__.py", line 87, in main
    boldblast_coi.main(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/boldigger_cline/boldblast_coi.py", line 14, in main
    session = login(username, password, certs)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/boldigger_cline/login.py", line 34, in login
    session.post("https://boldsystems.org/index.php/Login", data=data)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='boldsystems.org', port=443): Max retries exceeded with url: /index.php/Login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15537a6857c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
   


```

**Comment by Anto007** [comment] 2024-06-30 11:44
Update: I tried running boldigger-cline without specifying the batch size and it seems to be stuck at the Requesting BOLD stage since the past few minutes.

```
Login successful.
14:38:20: Requesting BOLD. This will take a while.                                                   
14:42:14: Downloading results.                                                                       
14:42:14: Parsing html.                                                                              
14:42:14: BOLD did not respond! Retrying.                                                            
14:42:14: Requesting BOLD. This will take a while.                                                   
Requesting BOLD:   0%|                                                        | 0/94 [03:54<?, ?it/s]

```

**Comment by DominikBuchner** [comment] 2024-06-30 16:14
Can you try to query the specified batch via the website? My assumption is, that we have a broken record here.

**Comment by DominikBuchner** [comment] 2024-06-30 17:24
Ah i already figured it. For Boldigger-cline you need it to format to 2-line fasta

**Comment by Anto007** [comment] 2024-06-30 17:43
Thanks again for your responnse @DominikBuchner  but sorry, I do not understand what you're saying. As I mentioned in the above post, the input fasta file was already formatted via seqkit (seqkit seq -w0 ASVs-no-contam-numts-final-clean.fa > 2line_ASVs-no-contam-numts-final-clean.fa). The process is at the 'Download' stage now I suppose. Perhaps, it will finish by later tonight. I'll try to update you on this tomorrow morning

**Comment by DominikBuchner** [comment] 2024-06-30 18:09
Ah okay, yeah I overread this one. Let's see how it goes.

**Comment by Anto007** [comment] 2024-06-30 18:14
Thanks and just in case you missed, I've also attached a fasta file in one of my earlier posts for your bench-marking efforts

**Comment by DominikBuchner** [comment] 2024-06-30 18:15
yes, it is already running.

**Comment by Anto007** [comment] 2024-07-01 05:35
My boldigger-cline (boldigger version 1) job for the same 4689 sequences that I shared with you finished in about 12 hours (I had to skip mentioning the batch size in the command-line to avoid the errors I mentioned in my previous post) while the boldigger2 task for the same set of sequences is still running into the 6th day

**Comment by DominikBuchner** [comment] 2024-07-02 04:51
I see. BOLDigger2 will take ~2 days for the whole dataset, BUT it will download almost 10-fold more data. It looks like the special issue of this dataset is that the majority of sequences (>80%) don't receive a species-level assignment after the first round. Therefore, every sequence will have to be identified twice, greatly increasing the runtime. I assume this is some kind of eDNA dataset? Anyways: I believe the longer runtime is justified, since the result will most probably be more precise. I also realised that BOLD hat some downtimes recently, which I cannot change but will break a webscraper regardless of the version used. 

IMHO: Greater runtime is justified if you have more accurate results. However, I'll try to keep BOLDigger and BOLDigger-cline up to date for the remainder of the year to make the transition easier.

**Closed as completed by DominikBuchner** 2024-07-02 04:51 UTC

**Comment by Anto007** [comment] 2024-07-02 05:20
Thank you for your feedback.Yes this is an eDNA dataset. Would you know why I get errors on BOLDigger-cline these days when I specify the batch size as 50 but not when I don't specify any batch-size. What is the default batch-size when nothing is specified? It used to run smoothly for me a couple of months back when  I used to specify batch-size as 50 for similar eDNA datasets. The below are the errors (as posted previously). 
```
boldigger-cline --version
2.2.1
boldigger-cline ie_coi username password 2line_ASVs-no-contam-numts-final-clean.fa boldigger1_results 50
Traceback (most recent call last):
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/tools/conda_python3.9_env/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x15537a6857c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='boldsystems.org', port=443): Max retries exceeded with url: /index.php/Login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15537a6857c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tools/conda_python3.9_env/bin/boldigger-cline", line 8, in <module>
    sys.exit(main())
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/boldigger_cline/__main__.py", line 87, in main
    boldblast_coi.main(
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/boldigger_cline/boldblast_coi.py", line 14, in main
    session = login(username, password, certs)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/boldigger_cline/login.py", line 34, in login
    session.post("https://boldsystems.org/index.php/Login", data=data)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tools/conda_python3.9_env/lib/python3.9/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='boldsystems.org', port=443): Max retries exceeded with url: /index.php/Login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15537a6857c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by DominikBuchner** [comment] 2024-07-02 06:03
Default batch size is 50, so this is confusing. I'll try to reproduce this,
however the error is kind of cryptic. Can you please try "pip install
--upgrade urllib3" and tell me if the error persists?

Jant007 ***@***.***> schrieb am Di., 2. Juli 2024, 07:20:

**Comment by Anto007** [comment] 2024-07-02 09:08
I retried BOLDigger-cline by specifying batch size of 50 (and without the urllib3 upgrade) but this time around, it did not give me those cryptic errors and the run was successful. Strange! There are some warnings such as 
"_FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(r.text, header = 0, converters = {'Similarity (%)': float}, flavor = 'html5lib')_" that I'm getting swamped with but I can definitely live with them ;-) Overall, I feel that I would be confident about running BOLDigger2 for smaller sequence datasets but would likely stick with boldigger-cline for the larger datasets. More eDNA sequence data are coming my way in the coming days or weeks and so I hope to be able to continue to use boldigger-cline or BOLDigger2 for them. Thank you again for all your fantastic support.

**Comment by DominikBuchner** [comment] 2024-07-03 04:55
I realized that I messed up the error handling for the additional data download, that's why it times out so often and takes so long. Will fix this ASAP, for me your ~5k Seq dataset finished in 30h, so not too bad.

**Comment by Anto007** [comment] 2024-07-03 07:01
That is a welcome development. I look forward to testing BOLDigger2 again once the fix is applied. Thank you again
