### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by voa257** [DominikBuchner/BOLDigger2#10] opened 2024-06-13 22:18 UTC
Hi, Dominik,

Recently, I've encountered an issue where the Boldigger2 shows the following error:

```
Calculating top hits:   0%|                                                                                                                                      | 0/183 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/victor/.pyenv/versions/3.10.14/bin/boldigger2", line 8, in <module>
    sys.exit(main())
  File "/Users/victor/.pyenv/versions/3.10.14/lib/python3.10/site-packages/boldigger2/__main__.py", line 87, in main
    id_engine_coi.main(
  File "/Users/victor/.pyenv/versions/3.10.14/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 674, in main
    digger_hit.main(
  File "/Users/victor/.pyenv/versions/3.10.14/lib/python3.10/site-packages/boldigger2/digger_hit.py", line 310, in main
    all_top_hits = Parallel(n_jobs=1)(
  File "/Users/victor/.pyenv/versions/3.10.14/lib/python3.10/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
  File "/Users/victor/.pyenv/versions/3.10.14/lib/python3.10/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/Users/victor/.pyenv/versions/3.10.14/lib/python3.10/site-packages/boldigger2/digger_hit.py", line 182, in find_top_hit
    threshold, level = move_threshold_up(threshold, thresholds)
  File "/Users/victor/.pyenv/versions/3.10.14/lib/python3.10/site-packages/boldigger2/digger_hit.py", line 65, in move_threshold_up
    thresholds[thresholds.index(threshold) + 1],
IndexError: list index out of range
```
As a result, it creates the following files in the directory:
- ...top_100_hits.h5.lz
- …top_100_hits_part_0.xlsx
- …download_links.h5.lz

However, the …identification_result.xlsx file is missing.

I run the following command:
`boldigger2 identify "/Volumes/T7_Shield/RAMX_SWARM13nc_seeds.fasta" -username [myusername] -password [mypassword] -thresholds 98 95 90 85 50`

I am attaching the FASTA file that I used, converted to .txt format to facilitate its upload here.
[RAMX_SWARM13nc_seeds.txt](https://github.com/user-attachments/files/15829302/RAMX_SWARM13nc_seeds.txt)

Best,

Víctor

**Comment by DominikBuchner** [comment] 2024-06-14 05:39
Hi Victor,

I'll try to replicate the issue and find out what the problem is. At the moment I have no clue but might be smth really specific about this dataset.

**Comment by DominikBuchner** [comment] 2024-06-14 07:34
Okay, I found it. Your sequence "RAMX_000009994"  has no associated class. I'm not sure if "Gastrotricha" do not have classes but I'm kind of hesitant to write a workaround for those cases. I could assign this to a NoMatch, but that is also not acurate. I'll think about this over the weekend. Any suggestions?

**Comment by OndroV** [comment] 2024-06-14 08:12
Yes there are groups without info at certain taxonomic level. It might be useful to have an option to automatically fill such "holes" with something like Gastrotricha_incertae_sedis.

**Comment by DominikBuchner** [comment] 2024-06-14 08:17
But how would you seperate this from actual garbage? At the moment I drop everything with numbers / specials because usually it is not useful data. However, if I do this at the class level, there is no higher level to go to. I think the cleanest way would be to insert a NoMatch or even cleaner to insert a new datatype sth like "IncompleteTaxonomy". Or is there actually useful information in "Gastrotricha_incertae_sedis"?

**Comment by voa257** [comment] 2024-06-14 11:13
I propose that a term like "IncompleteTaxonomy" would be more appropriate, as this situation does not qualify as a "NoMatch". Although "Gastrotricha_incertae_sedis" provides some taxonomic context, it remains somewhat uninformative.

**Comment by DominikBuchner** [comment] 2024-06-14 11:45
Yes does make sense! Do all gastroticha not have a class?!

**Comment by DominikBuchner** [comment] 2024-06-14 11:47
I think this case will also be very, very rare, so checking those entries by hand if "IncompleteTaxnonomy" is returned should be doable!

**Comment by voa257** [comment] 2024-06-14 15:21
It appears that the phylum Gastrotricha is classified into Orders without mentioning any level of Class.

Are you suggesting that a method to handle these rare cases could be implemented in Boldigger2?

By the way, I noticed some typos in the terminal prompts of Boldigger2, where taxonomic levels are listed as Species, Genus, Family, Genus, Species. You can check this in your README.md file.

```
19:16:16: Default thresholds changed!
19:16:16: Species: 99, Genus: 97, Family: 90, Genus: 85, Species: 50
19:16:16: Trying to log in.
BOLD username:
```

**Comment by DominikBuchner** [comment] 2024-06-14 15:28
Uh yes, I will fix those as well. I will handle those cases where the taxonomic annotation is incomplete. Update will follow soon

**Comment by DominikBuchner** [comment] 2024-06-14 17:18
Hi Victor,
the issue is fixed now, I introduced the "IncompleteTaxonomy" type. Also fixed the typos. You can find your identification result here:
[RAMX_SWARM13nc_seeds_identification_result.xlsx](https://github.com/user-attachments/files/15841434/RAMX_SWARM13nc_seeds_identification_result.xlsx)

Let me know if anything else does not work with BOLDigger2 but first have a nice weekend.
best
Dominik

**Closed as completed by DominikBuchner** 2024-06-14 17:18 UTC
