### ISSUE TITLE
Not assigning ranks lower than species level

### ISSUE THREAD

**Issue by eershova01** [DominikBuchner/BOLDigger2#22] opened 2024-08-03 16:43 UTC
Hi, thanks for your great program! In the new version, I am not getting any identifications higher than species level. Take for example this sequence:

>COMB_000009819
actttcaagtaatattgctcatgctggtagagctgttgactttgctattttttctcttcatcttgctggtgcaaggtctattttaggggcagtaaactttatttctactgttggtaaccttcgttcctttggtataatagcagacctcataccactatttaggtgggctgtagtaattacagctgtattacttttattgtctttaccagtactggctggggcaattactatacttttaactgatcgaaatttaaactcttctttttatgatgcggggggtgggggagaccctattctttaccaacaccttttt

In the final table it just says NoMatch, but if you run it manually within BOLD it has 20+ matches of 80% or more in the All Sequences database, including 3 of 90% or more (should be assigned as family level). This is the case for every sequence in my fasta, no exceptions. Is there something I am missing in the code? The previous version of Boldigger successfully assigned higher ranks.

**Comment by DominikBuchner** [comment] 2024-08-04 07:44
Can you please upload the fasta so I can check this?

eershova01 ***@***.***> schrieb am Sa., 3. Aug. 2024, 18:44:

**Comment by eershova01** [comment] 2024-08-04 07:46
[mats20.fasta.txt](https://github.com/user-attachments/files/16486759/mats20.fasta.txt)

**Comment by DominikBuchner** [comment] 2024-08-04 07:47
With the recent updates on the website strange things happen will see what
I can do

Dominik Buchner ***@***.***> schrieb am So., 4. Aug.
2024, 09:44:

**Comment by eershova01** [comment] 2024-08-04 08:13
Another issue I noticed: when the API server gets overloaded, the program says "trying again in a few minutes" and then waits 10 minutes, but no matter how many times it tries server remains overloaded so that just repeats on a loop forever. It ran overnight, and didn't get anywhere. I killed the process and started over, and it connected OK immediately, so it wasn't because the served was down. 

Maybe instead of trying again in 10 minutes, it could log out/log in again to somehow reset the process?

**Comment by DominikBuchner** [comment] 2024-08-04 08:39
A login is not required for the API, I'll also check this... I really hope most of those issues will be fixed with BOLDv5, at the moment it's really a pain.

**Comment by DominikBuchner** [comment] 2024-08-04 08:58
Okay, I think you spotted a bug here with the missing 80% assignments I can reproduce it and think I know the reason. I'll let you know as soon as I fixed it.

**Comment by eershova01** [comment] 2024-08-04 09:09
Thank you!! And thanks for the quick responses (especially on a Sunday!)

**Comment by DominikBuchner** [comment] 2024-08-04 09:36
Fixed with 2.0.5. It should work as expected now (see example file). Have a nice rest of your weekend :)

[mats20.fasta_identification_result.xlsx](https://github.com/user-attachments/files/16487026/mats20.fasta_identification_result.xlsx)

**Closed as completed by DominikBuchner** 2024-08-04 09:36 UTC

**Comment by eershova01** [comment] 2024-08-04 15:54
Thank you - works perfect now!
